name: PHPStan

on:
    push:
        paths:
            - '**.php'
            - 'phpstan.neon'

jobs:
    phpstan:
        name: phpstan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap
                  coverage: none
            
            - name: Install dependencies
              run: |
                  composer require --no-interaction --no-update php-ffmpeg/php-ffmpeg
                  composer update --no-interaction --prefer-dist
            
            - name: Run PHPStan
              run: ./vendor/bin/phpstan
